apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip-service-ingress
  namespace: ip-service
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ip.sanjith.dev    # you can change or use nip.io for demo
    secretName: ip-service-tls
  rules:
  - host: ip.sanjith.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ip-service
            port:
              number: 80
